name: style-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          repository: 'https://github.com/spack/spack' # clone spack repo
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade pip six setuptools types-six click==8.0.2 'black==21.12b0' mypy isort clingo flake8
      - name: Setup git configuration
        run: |
          # Need this for the git tests to succeed.
          git --version
          . .github/workflows/setup_git.sh
# clone octopus-in-spack repo and copy the package.py file to the spack repo
      - name: Clone octopus-in-spack repo
        run: |
          git clone https://github.com/fangohr/octopus-in-spack octopus-in-spack
          cp octopus-in-spack/spack/package.py spack/var/spack/repos/builtin/packages/octopus/package.py
      - name: Run style tests
        run: |
            share/spack/qa/run-style-tests